services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}

        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

        AUTH_SECRET: ${AUTH_SECRET}
        AUTH_URL: ${AUTH_URL}

        ENCRYPTION_KEY: ${ENCRYPTION_KEY}

        RESEND_API_KEY: ${RESEND_API_KEY}
        RESEND_FROM_EMAIL: ${RESEND_FROM_EMAIL}
        EMAIL_DESTINATARIO_DEV: ${EMAIL_DESTINATARIO_DEV}
  
    image: template-next-app:latest
    container_name: template-next-app
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    env_file:
      - .env

    environment:
      NODE_ENV: production
      TZ: America/Sao_Paulo

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "3000:3000"

  mysql:
    image: mysql:8.4
    container_name: template-next-mysql
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: America/Sao_Paulo

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:
